FROM node:21-alpine
WORKDIR /src/user-service
COPY package*.json ./
RUN npm install
COPY . .

ARG DB_URL
ARG AWS_REGION
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG AWS_S3_BUCKET

ENV DB_URL=$DB_URL
ENV AWS_REGION=$AWS_REGION
ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_KEY=$AWS_SECRET_KEY
ENV AWS_S3_BUCKET=$AWS_S3_BUCKET

EXPOSE 3001
CMD ["npm", "run", "start:prod"]