name: User Service CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build Docker image
              run: |
                    docker build \
                    --build-arg DB_URL=${{ secrets.DB_URL }} \
                    --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
                    --build-arg AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
                    --build-arg AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
                    --build-arg AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
                    -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest .
            
            - name: Push Docker image to Docker Hub
              run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest